// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	goth "github.com/markbates/goth"
	mock "github.com/stretchr/testify/mock"
)

// IOAuthUsecase is an autogenerated mock type for the IOAuthUsecase type
type IOAuthUsecase struct {
	mock.Mock
}

// HandleOAuthUserFacebook provides a mock function with given fields: user
func (_m *IOAuthUsecase) HandleOAuthUserFacebook(user goth.User) (string, error) {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for HandleOAuthUserFacebook")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(goth.User) (string, error)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(goth.User) string); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(goth.User) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandleOAuthUserGoogle provides a mock function with given fields: user
func (_m *IOAuthUsecase) HandleOAuthUserGoogle(user goth.User) (string, error) {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for HandleOAuthUserGoogle")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(goth.User) (string, error)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(goth.User) string); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(goth.User) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIOAuthUsecase creates a new instance of IOAuthUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIOAuthUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IOAuthUsecase {
	mock := &IOAuthUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
