// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	context "context"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	model "th3y3m/e-commerce-microservices/service/payment/model"

	repository "th3y3m/e-commerce-microservices/service/payment/repository"
)

// IPaymentRepository is an autogenerated mock type for the IPaymentRepository type
type IPaymentRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, payment
func (_m *IPaymentRepository) Create(ctx context.Context, payment *repository.Payment) (*repository.Payment, error) {
	ret := _m.Called(ctx, payment)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *repository.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *repository.Payment) (*repository.Payment, error)); ok {
		return rf(ctx, payment)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *repository.Payment) *repository.Payment); ok {
		r0 = rf(ctx, payment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *repository.Payment) error); ok {
		r1 = rf(ctx, payment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, paymentID
func (_m *IPaymentRepository) Delete(ctx context.Context, paymentID int64) error {
	ret := _m.Called(ctx, paymentID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, paymentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, paymentID
func (_m *IPaymentRepository) Get(ctx context.Context, paymentID int64) (*repository.Payment, error) {
	ret := _m.Called(ctx, paymentID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *repository.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*repository.Payment, error)); ok {
		return rf(ctx, paymentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *repository.Payment); ok {
		r0 = rf(ctx, paymentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, paymentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: ctx
func (_m *IPaymentRepository) GetAll(ctx context.Context) ([]*repository.Payment, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*repository.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*repository.Payment, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*repository.Payment); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*repository.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetList provides a mock function with given fields: ctx, req
func (_m *IPaymentRepository) GetList(ctx context.Context, req *model.GetPaymentsRequest) ([]*repository.Payment, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetList")
	}

	var r0 []*repository.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.GetPaymentsRequest) ([]*repository.Payment, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.GetPaymentsRequest) []*repository.Payment); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*repository.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.GetPaymentsRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, payment
func (_m *IPaymentRepository) Update(ctx context.Context, payment *repository.Payment) (*repository.Payment, error) {
	ret := _m.Called(ctx, payment)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *repository.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *repository.Payment) (*repository.Payment, error)); ok {
		return rf(ctx, payment)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *repository.Payment) *repository.Payment); ok {
		r0 = rf(ctx, payment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *repository.Payment) error); ok {
		r1 = rf(ctx, payment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// getQuerySearch provides a mock function with given fields: db, req
func (_m *IPaymentRepository) getQuerySearch(db *gorm.DB, req *model.GetPaymentsRequest) *gorm.DB {
	ret := _m.Called(db, req)

	if len(ret) == 0 {
		panic("no return value specified for getQuerySearch")
	}

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func(*gorm.DB, *model.GetPaymentsRequest) *gorm.DB); ok {
		r0 = rf(db, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}

// NewIPaymentRepository creates a new instance of IPaymentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIPaymentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IPaymentRepository {
	mock := &IPaymentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
