// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	context "context"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	model "th3y3m/e-commerce-microservices/service/news/model"

	repository "th3y3m/e-commerce-microservices/service/news/repository"
)

// INewRepository is an autogenerated mock type for the INewRepository type
type INewRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, new
func (_m *INewRepository) Create(ctx context.Context, new *repository.News) (*repository.News, error) {
	ret := _m.Called(ctx, new)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *repository.News
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *repository.News) (*repository.News, error)); ok {
		return rf(ctx, new)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *repository.News) *repository.News); ok {
		r0 = rf(ctx, new)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.News)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *repository.News) error); ok {
		r1 = rf(ctx, new)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, newID
func (_m *INewRepository) Delete(ctx context.Context, newID int64) error {
	ret := _m.Called(ctx, newID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, newID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, newID
func (_m *INewRepository) Get(ctx context.Context, newID int64) (*repository.News, error) {
	ret := _m.Called(ctx, newID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *repository.News
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*repository.News, error)); ok {
		return rf(ctx, newID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *repository.News); ok {
		r0 = rf(ctx, newID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.News)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, newID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: ctx
func (_m *INewRepository) GetAll(ctx context.Context) ([]*repository.News, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*repository.News
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*repository.News, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*repository.News); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*repository.News)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetList provides a mock function with given fields: ctx, req
func (_m *INewRepository) GetList(ctx context.Context, req *model.GetNewsRequest) ([]*repository.News, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetList")
	}

	var r0 []*repository.News
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.GetNewsRequest) ([]*repository.News, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.GetNewsRequest) []*repository.News); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*repository.News)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.GetNewsRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, new
func (_m *INewRepository) Update(ctx context.Context, new *repository.News) (*repository.News, error) {
	ret := _m.Called(ctx, new)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *repository.News
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *repository.News) (*repository.News, error)); ok {
		return rf(ctx, new)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *repository.News) *repository.News); ok {
		r0 = rf(ctx, new)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.News)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *repository.News) error); ok {
		r1 = rf(ctx, new)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// getQuerySearch provides a mock function with given fields: db, req
func (_m *INewRepository) getQuerySearch(db *gorm.DB, req *model.GetNewsRequest) *gorm.DB {
	ret := _m.Called(db, req)

	if len(ret) == 0 {
		panic("no return value specified for getQuerySearch")
	}

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func(*gorm.DB, *model.GetNewsRequest) *gorm.DB); ok {
		r0 = rf(db, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}

// NewINewRepository creates a new instance of INewRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewINewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *INewRepository {
	mock := &INewRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
