// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	context "context"
	repository "th3y3m/e-commerce-microservices/service/discount/repository"

	mock "github.com/stretchr/testify/mock"
)

// IDiscountRepository is an autogenerated mock type for the IDiscountRepository type
type IDiscountRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, discount
func (_m *IDiscountRepository) Create(ctx context.Context, discount *repository.Discount) (*repository.Discount, error) {
	ret := _m.Called(ctx, discount)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *repository.Discount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *repository.Discount) (*repository.Discount, error)); ok {
		return rf(ctx, discount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *repository.Discount) *repository.Discount); ok {
		r0 = rf(ctx, discount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Discount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *repository.Discount) error); ok {
		r1 = rf(ctx, discount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, discountID
func (_m *IDiscountRepository) Delete(ctx context.Context, discountID int64) error {
	ret := _m.Called(ctx, discountID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, discountID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, discountID
func (_m *IDiscountRepository) Get(ctx context.Context, discountID int64) (*repository.Discount, error) {
	ret := _m.Called(ctx, discountID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *repository.Discount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*repository.Discount, error)); ok {
		return rf(ctx, discountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *repository.Discount); ok {
		r0 = rf(ctx, discountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Discount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, discountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: ctx
func (_m *IDiscountRepository) GetAll(ctx context.Context) ([]*repository.Discount, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*repository.Discount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*repository.Discount, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*repository.Discount); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*repository.Discount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, discount
func (_m *IDiscountRepository) Update(ctx context.Context, discount *repository.Discount) (*repository.Discount, error) {
	ret := _m.Called(ctx, discount)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *repository.Discount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *repository.Discount) (*repository.Discount, error)); ok {
		return rf(ctx, discount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *repository.Discount) *repository.Discount); ok {
		r0 = rf(ctx, discount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Discount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *repository.Discount) error); ok {
		r1 = rf(ctx, discount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIDiscountRepository creates a new instance of IDiscountRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIDiscountRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IDiscountRepository {
	mock := &IDiscountRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
