// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	context "context"
	repository "th3y3m/e-commerce-microservices/service/freight_rate/repository"

	mock "github.com/stretchr/testify/mock"
)

// IFreightRateRepository is an autogenerated mock type for the IFreightRateRepository type
type IFreightRateRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, freightRate
func (_m *IFreightRateRepository) Create(ctx context.Context, freightRate *repository.FreightRate) (*repository.FreightRate, error) {
	ret := _m.Called(ctx, freightRate)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *repository.FreightRate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *repository.FreightRate) (*repository.FreightRate, error)); ok {
		return rf(ctx, freightRate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *repository.FreightRate) *repository.FreightRate); ok {
		r0 = rf(ctx, freightRate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.FreightRate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *repository.FreightRate) error); ok {
		r1 = rf(ctx, freightRate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, freightRateID
func (_m *IFreightRateRepository) Delete(ctx context.Context, freightRateID int64) error {
	ret := _m.Called(ctx, freightRateID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, freightRateID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, freightRateID
func (_m *IFreightRateRepository) Get(ctx context.Context, freightRateID int64) (*repository.FreightRate, error) {
	ret := _m.Called(ctx, freightRateID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *repository.FreightRate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*repository.FreightRate, error)); ok {
		return rf(ctx, freightRateID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *repository.FreightRate); ok {
		r0 = rf(ctx, freightRateID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.FreightRate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, freightRateID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: ctx
func (_m *IFreightRateRepository) GetAll(ctx context.Context) ([]*repository.FreightRate, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*repository.FreightRate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*repository.FreightRate, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*repository.FreightRate); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*repository.FreightRate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, freightRate
func (_m *IFreightRateRepository) Update(ctx context.Context, freightRate *repository.FreightRate) (*repository.FreightRate, error) {
	ret := _m.Called(ctx, freightRate)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *repository.FreightRate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *repository.FreightRate) (*repository.FreightRate, error)); ok {
		return rf(ctx, freightRate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *repository.FreightRate) *repository.FreightRate); ok {
		r0 = rf(ctx, freightRate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.FreightRate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *repository.FreightRate) error); ok {
		r1 = rf(ctx, freightRate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIFreightRateRepository creates a new instance of IFreightRateRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIFreightRateRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IFreightRateRepository {
	mock := &IFreightRateRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
