// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IAuthUsecase is an autogenerated mock type for the IAuthUsecase type
type IAuthUsecase struct {
	mock.Mock
}

// Login provides a mock function with given fields: email, password
func (_m *IAuthUsecase) Login(email string, password string) (string, error) {
	ret := _m.Called(email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(email, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(email, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterCustomer provides a mock function with given fields: email, password, confirmPassword
func (_m *IAuthUsecase) RegisterCustomer(email string, password string, confirmPassword string) error {
	ret := _m.Called(email, password, confirmPassword)

	if len(ret) == 0 {
		panic("no return value specified for RegisterCustomer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(email, password, confirmPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VerifyUserEmail provides a mock function with given fields: token
func (_m *IAuthUsecase) VerifyUserEmail(token string) error {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyUserEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIAuthUsecase creates a new instance of IAuthUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAuthUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAuthUsecase {
	mock := &IAuthUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
